routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/*
|--------------------------------------------------------------------------
| ☢️ Test Zone
|--------------------------------------------------------------------------
*/

Route::group( ['middleware' => ['permission:admin-level']], function() {
    Route::get('/test/isotope', 'Test\FrontendController@isotope')->name('test.isotope');
    Route::get('/test/isotope-sorting', 'Test\FrontendController@isotopeSorting')->name('test.isotope.sorting');
    Route::get('/test/dhl', 'Test\FrontendController@dhl')->name('test.dhl');
    Route::get('/test/grid', 'Test\FrontendController@grid')->name('test.grid');
    
    Route::get('/test/api', 'Test\FrontendController@api')->name('test.api');
    Route::post('/test/api', 'Test\FrontendController@api')->name('test.api');
    Route::post('/test/api2', 'Test\FrontendController@api2')->name('test.api2');
    
    Route::get('/test/mail/{type}/{mail_kind}/{id}', 'Test\FrontendController@mail');
    Route::get('/test/allmail/', 'Test\FrontendController@allmail')->name('all.mail');
    
    Route::get('/test/search', 'Test\FrontendController@search')->name('test.search');
    
});


/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------
*/

// Home
Route::get('/', 'Home\FrontendController@index')->name('home');
Route::get('/home', 'Home\FrontendController@index')->name('home');

// Artworks
//Route::get('/artworks/view/intro', 'Artworks\FrontendController@intro')->name('artworks.intro'); // Artworks Intro
Route::get('/artworks', 'Artworks\FrontendController@archive')->name('artworks.archive.all'); // Artworks Archive All
Route::get('/artworks/{slug_name}', 'Artworks\FrontendController@single')->name('artworks.single'); // Artworks Single
Route::get('/artworks/{slug_medium}/{slug_category}', 'Artworks\FrontendController@archive')->name('artworks.categories.medium'); // Artworks Single
Route::post('/artworks/get/filtered/items', 'Artworks\FrontendController@getFilteredItems')->name('artworks.get.filtered.items'); // Artworks filter

// Galleries
Route::get('/galleries', 'Galleries\FrontendController@intro')->name('galleries.intro'); // Artworks Intro
Route::get('/galleries/archive', 'Galleries\FrontendController@archive')->name('galleries.archive.all'); // Artworks Archive All
Route::post('/galleries/load/more', 'Galleries\FrontendController@loadMore')->name('galleries.load.more'); // Artworks Archive All
Route::get('/galleries/{slug_name}', 'Galleries\FrontendController@single')->name('galleries.single'); // Artworks Single
Route::post('/galleries/search/by', 'Galleries\FrontendController@searchBy')->name('galleries.search.by'); // Artworks Archive All
Route::post('/galleries/request/subscription', 'Galleries\FrontendController@requestSubscription')->name('galleries.request.subscription');
// Artists
Route::get('/artists', 'Artists\FrontendController@intro')->name('artists.intro'); // Artworks Intro
Route::get('/artists/archive', 'Artists\FrontendController@archive')->name('artists.archive.all'); // Artworks Archive All
Route::post('/artists/load/more', 'Artists\FrontendController@loadMore')->name('artists.load.more'); // Artworks Archive All
Route::get('/artists/{slug_name}', 'Artists\FrontendController@single')->name('artists.single'); // Artworks Single
Route::post('/artists/search/by', 'Artists\FrontendController@searchBy')->name('artists.search.by'); // Artworks Archive All

// Fairs
Route::get('/fairs', 'Fairs\FrontendController@intro')->name('fairs.intro'); // Fairs Intro
Route::get('/fairs/archive', 'Fairs\FrontendController@archive')->name('fairs.archive.all'); // Fairs Archive All
Route::get('/fairs/{slug_name}', 'Fairs\FrontendController@single')->name('fairs.single'); // Fairs Single

// Posts Magazine / News
Route::get('/posts/{section}', 'Posts\FrontendController@archive')->name('posts.archive.all'); // Posts Archive All
Route::get('/posts/{section}/{slug_name}', 'Posts\FrontendController@single')->name('posts.single'); // Posts Single
Route::post('/posts/{section}/load/more', 'Posts\FrontendController@loadMore')->name('posts.load.more'); // Posts Single

// Static Pages
Route::get('/pages/{slug_name}', 'Pages\FrontendController@pages')->name('pages.intro'); // Users profile

// Exhibitions
Route::get('/exhibitions', 'Exhibitions\FrontendController@archive')->name('exhibitions.archive'); // Archive
Route::get('/exhibitions/{slug_name}', 'Exhibitions\FrontendController@single')->name('exhibitions.single'); // Single
Route::post('/exhibitions/load/more', 'Exhibitions\FrontendController@loadMore')->name('exhibitions.load.more'); // Posts Single

// Tags
Route::get('/tags/{slug_name}/{type?}', 'Tags\FrontendController@single')->name('tags.single'); // Tags Single
Route::post('/tags/{section}/load/more', 'Tags\FrontendController@loadMore')->name('tags.load.more'); // Tags Single

Route::post('/search', 'FrontendController@search')->name('search'); // Posts Single
Route::get('/get/currency/{currency}', 'FrontendController@getCurrency')->name('get.currency'); // Posts Single
Route::post('/apply/promo/code', 'FrontendController@applyPromoCode')->name('apply.promo.code');
Route::post('/remove/promo/code', 'FrontendController@removePromoCode')->name('remove.promo.code');

// Access User
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login.get');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('/activate/{token}', 'Auth\RegisterController@verifyUser')->name('verify_user');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/auth/{provider}', 'Auth\SocialController@redirectToProvider')->name('auth.social');
Route::get('/auth/{provider}/callback', 'Auth\SocialController@handleProviderCallback')->name('auth.social.callback');

// User Routes
//Route::group(['middleware' => ['permission:user-level']], function () {
//    Route::get('/user/page', 'Users\FrontendController@profile')->name('user.profile');
//    Route::post('/user/page', 'Users\FrontendController@profile')->name('user.profile');
//});

Route::post('/add/to/cart', 'Orders\FrontendController@addToCart')->name('orders.add.to.cart'); // Add to cart
Route::post('/remove/from/cart', 'Orders\FrontendController@removeFromCart')->name('orders.remove.from.cart'); // Remove from cart
Route::get('/cart', 'Orders\FrontendController@cart')->name('orders.cart'); // Add to cart
Route::get('/paypal', 'Orders\FrontendController@payPalReturn')->name('orders.paypal.callback'); // Thank you page

Route::post('/subscribe/to/newsletter', 'FrontendController@subscribeToNewsletter')->name('subscribe.to.newsletter');
Route::get('/subscription/newsletter/thank-you', 'FrontendController@subscriptionNewsletterThankYou')->name('subscription.newsletter.thank.you');

Route::post('/send/contact/message', 'FrontendController@sendContactMessage')->name('send.contact.message');
Route::get('/pay/order/{token}', 'Orders\FrontendController@payOrder')->name('orders.pay.order'); // Checkout


Route::get('/google/shopping/feed.xml', 'FrontendController@googleFeed')->name('google.feed'); // Checkout

Route::group(['middleware' => ['permission:user-level']], function () {
    //Orders
    Route::post('/get/shipping/rate', 'Orders\FrontendController@getShippingRate')->name('orders.get.shipping.rate');
    Route::get('/checkout', 'Orders\FrontendController@viewCheckout')->name('orders.view.checkout'); // Checkout
    Route::post('/checkout', 'Orders\FrontendController@checkout')->name('orders.checkout'); // Checkout
    Route::post('/checkout/pay', 'Orders\FrontendController@checkoutPay')->name('orders.checkout.pay'); // Checkout
    Route::get('/thank-you', 'Orders\FrontendController@thankYouPage')->name('orders.thank.you'); // Thank you page
    Route::get('/order/pending/thank-you', 'Orders\FrontendController@thankYouPageWithoutPayment')->name('orders.thank.you.without.payment'); // Thank you page
    Route::get('/payment/error', 'Orders\FrontendController@paymentError')->name('orders.payment.error'); // Thank you page

    Route::post('/user/ajax/save/address', 'Users\FrontendController@saveAddress')->name('users.save.address');
    Route::post('/user/ajax/save/payment', 'Users\FrontendController@savePaymentMethod')->name('users.save.payment');
    Route::post('/user/ajax/delete/address', 'Users\FrontendController@deleteAddress')->name('users.delete.address');
    Route::post('/user/ajax/delete/payment', 'Users\FrontendController@deletePaymentMethod')->name('users.delete.payment');
    Route::post('/user/ajax/promo/code', 'Users\FrontendController@applyPromoCode')->name('users.apply.promo.code');
    Route::post('/user/ajax/promo/code/remove', 'Users\FrontendController@removePromoCode')->name('users.remove.promo.code');
    Route::post('/user/ajax/add/to/collection', 'Users\FrontendController@addToCollection')->name('users.add.to.collection');

app/Models/Artwork.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class Artwork extends Model
{
    protected $guarded = [];

    protected $appends = ['tag_ids', 'category_ids', 'fair_ids', 'gallery_name', 'artist_name', 'pretty_price'];

    protected $fillable = [
        'artist_id',
        'gallery_id',
        'created_by',
        'reference',
        'title',
        'slug',
        'from_the_series', 
        'year',
        'width',
        'height',
        'depth',
        'weight',
        'single_piece',
        'signed',
        'dated',
        'titled',
        'framed',
        'available_in_fair',
        'show_price',
        'about_the_work',
        'news',
        'status',
        'price',
        'taxable',
        'vat',
        'current_city',
        'current_zip',
        'current_country',
        'meta_title',
        'h1',
        'canonical',
        'meta_keywords',
        'meta_description',
    ];

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'artworks_tags', 'artwork_id', 'tag_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Models\ArtworksCategory', 'artworks_artworks_categories', 'artwork_id', 'category_id');
    }


    public function medium()
    {
        return $this->belongsToMany('App\Models\ArtworksCategory', 'artworks_artworks_categories', 'artwork_id', 'category_id');
    }

    public function fairs()
    {
        return $this->belongsToMany('App\Models\Fair', 'artworks_fairs', 'artwork_id', 'fair_id');
    }

    public function artist()
    {
        return $this->hasOne('App\Models\Artist', 'id', 'artist_id');
    }

    public function gallery()
    {
        return $this->hasOne('App\Models\Gallery', 'id', 'gallery_id');
    }

    public function images()
    {
        return $this->hasMany('App\Models\ArtworksImage', 'artwork_id', 'id');
    }

    public function country()
    {
        return $this->hasOne('App\Models\Country', 'id', 'current_country');
    }

    public function news(){
        return $this->belongsToMany('App\Models\Post', 'posts_artworks', 'artwork_id', 'post_id');
    }

    public function getTagIdsAttribute()
    {
        return $this->tags->pluck('id')->toArray();
    }

    public function getCategoryIdsAttribute()
    {
        return $this->categories->pluck('id')->toArray();
    }

    public function getFairIdsAttribute()
    {
        return $this->fairs->pluck('id')->toArray();
    }

    public function getGalleryNameAttribute()
    {
        return $this->gallery()->first()->name;
    }

    public function getArtistNameAttribute()
    {
        $artist = $this->artist()->first();
        return $artist->last_name . " " . $artist->first_name;
    }

    public function getMediumStringAttribute()
    {
        $medium = $this->categories()->whereIsMedium(1)->pluck('name')->toArray();
        return implode(', ', $medium);
    }

    public function getMeasureCmAttribute()
    {
        return $this->width . ' x ' . $this->height . (($this->depth ? ' x ' . $this->depth : ''));
    }

    public function getMeasureIncAttribute()
    {
        return number_format(round($this->width/2.54, 2 ),2,'.',''). ' x ' . number_format(number_format(round($this->height/2.54, 2 ),2,'.','')) . (($this->depth ? ' x ' . number_format(round($this->depth/2.54, 2 ),2,'.','') : ''));
    }

    public function getNewsAttribute($value)
    {
        return $value;
    }

    public function getPrettyPriceAttribute()
    {
        $request = request();
        if(!$request->is('admin*')){
            if(Auth::user()) {
                $offer = Auth::user()->offers()->whereArtworkId($this->id)->whereStatus(2)->first();
                if($offer){
                    return number_format($offer->amount, '2', ',', '') . " €";
                }
            }
        }
        return number_format($this->price, '2', ',', '') . " €";
    }

    public function getPriceAttribute($value)
    {
        $request = request();
        if(!$request->is('admin*')){
            if(Auth::user()) {
                $offer = Auth::user()->offers()->whereArtworkId($this->id)->whereStatus(2)->first();
                if($offer){
                    return $offer->amount;
                }
            }
        }
        return $value;
    }

    public function getMainImageAttribute(){
        $image = $this->images()->orderBy('label', 'ASC')->first();
        if(!$image){
            $image = new ArtworksImage();
            $image->url = url('/images/placeholder-square-box.jpg');

            return $image;
        }
        return $image;
    }

    public function getUrlSquareBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-square-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getUrlWideBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-wide-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getUrlVerticalBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-vertical-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getSlugAttribute($value){
        return trim($value);
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $guarded = [];

    public function artworks(){
        return $this->belongsToMany('App\Models\Artwork', 'artworks_tags', 'tag_id', 'artwork_id')->whereRaw('status IN (1,2)');
    }

    public function artists(){
        return $this->belongsToMany('App\Models\Artist', 'artists_tags', 'tag_id', 'artist_id')->whereStatus(1);
    }

    public function galleries(){
        return $this->belongsToMany('App\Models\Gallery', 'galleries_tags', 'tag_id', 'gallery_id')->whereStatus(1);
    }

    public function news(){
        return $this->belongsToMany('App\Models\Post', 'posts_tags', 'tag_id', 'post_id')->whereType('news')->whereStatus(1);
    }

    public function magazine(){
        return $this->belongsToMany('App\Models\Post', 'posts_tags', 'tag_id', 'post_id')->whereType('magazine')->whereStatus(1);
    }

    public function getSlugAttribute($value){
        return trim($value);
    }
}

app/Http/Controllers/PromoCodes/FrontendController.php
<?php

namespace App\Http\Controllers\PromoCodes;

use App\Http\Controllers\FrontendExtendedController;
use Request;
use Validator;

class FrontendController extends FrontendExtendedController
{
    /**
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }
}

resources/views/orders/frontend/cart.blade.php
@extends('layouts.app')

@section('title')
    Cart
@endsection

@section('body-class')
    cart
@endsection

@section('seo-customs-scripts')
    <script>
        window.addEventListener('load', function() {
            // Initiate Checkout button
            var initiateCheckoutButton = document.getElementById('initiateCheckoutButton');
            if(initiateCheckoutButton)
                initiateCheckoutButton.addEventListener(
                    'click',
                    function() {

                        // For facebook pixel
                        fbq('track', 'InitiateCheckout');
                        console.log('Facebook Pixel "Intiate Checkout" triggered!');

                        // For Google Analytics
                        ga('send', 'event', 'Funnel', 'Intiate Checkout');
                        console.log('Google Analytics "Intiate Checkout" triggered!');

                    },
                    false
                );
        });
    </script>
@endsection

@section('content')
    <section class="sections">
        <section id="page-header">
            <div class="container boxed-container">
                <div class="col-container-with-offset">
                    <div class="default-sheet-row">
                        <div class="default-sheet-row-cell">
                            <h1>Purchase</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="cart">
            <div class="boxed-container">
                <div class="col-container container-vertical-padding-bottom container-vertical-padding-top">
                    @if($cart->items()->count())
                        @foreach($cart->items()->get() as $item)
                            <?php
                            $product = $item->product;
                            $casual_transfer[] = $item->product->title;
                            ?>
                            <div class="full-col-with-margin cart-item">
                                <div class="col-container">
                                    <div class="one-third-col-with-margin">
                                        <div class="cart-product-img">
                                            <a href="{{ route('artworks.single', [$product->slug]) }}" class="cart-thumb">
                                                <img data-src="{{ $product->main_image->url }}" src="" class="lazy"> </a>
                                        </div>
                                    </div>
                                    <div class="two-third-col-with-margin">
                                        <form method="POST" action="{{ route('orders.remove.from.cart') }}">
                                            @csrf
                                            <input type="hidden" value="{{ $product->id }}" name="id">
                                            <a onclick="this.parentNode.submit()" title="Remove" class="red-text remove">Remove</a>
                                        </form>
                                        <div class="default-sheet-box">
                                            <div class="default-sheet-row">
                                                <div class="default-sheet-row-cell">
                                                    <h3 class="no-margin">
                                                        <a title="{{ $product->artist_name }}" class="dark-text" href="{{ route('artists.single', [$product->artist->slug]) }}">{{ $product->artist_name }}</a>
                                                    </h3>
                                                </div>

                                                @if(Auth::user())
                                                <a class="follow secondary-link {{ (Auth::user()->collectionArtworks->contains($product->id)) ? 'active' : '' }}" data-section="artworks" data-id="{{$product->id}}">
                                                    @if(Auth::user()->collectionArtworks->contains($product->id))
                                                        <i class="fa fa-heart"> </i>
                                                        <span class="follow-unfollow">
                                                            Unfollow
                                                        </span>
                                                    @else
                                                        <i class="fa fa-heart-o"> </i>
                                                        <span class="follow-unfollow">
                                                            Follow
                                                        </span>
                                                    @endif
                                                </a>
                                                @endif

                                            </div>
                                            <div class="default-sheet-row">
                                                <span class="h1" class="no-margin">{{ $product->title }}</span>
                                            </div>
                                        </div>
                                        <div class="default-sheet-box">
                                            <div class="default-sheet-row">
                                                <div class="default-sheet-row-cell">
                                                    <p class="dark-text"><strong>Reference</strong></p>
                                                </div>
                                                <div class="default-sheet-row-cell">
                                                    <p>{{ $product->reference }}</p>
                                                </div>
                                            </div>
                                            <div class="default-sheet-row">
                                                <div class="default-sheet-row-cell">
                                                    <p class="dark-text"><strong>Year</strong></p>
                                                </div>
                                                <div class="default-sheet-row-cell">
                                                    <p>{{ $product->year }}</p>
                                                </div>
                                            </div>
                                            <div class="default-sheet-row">
                                                <div class="default-sheet-row-cell">
                                                    <p class="dark-text"><strong>Medium</strong></p>
                                                </div>
                                                <div class="default-sheet-row-cell">
                                                    <p>{{ $product->medium_string }}</p>
                                                </div>
                                            </div>
                                            <div class="default-sheet-row">
                                                <div class="default-sheet-row-cell">
                                                    <p class="dark-text"><strong>Size</strong></p>
                                                </div>
                                                <div class="default-sheet-row-cell">
                                                    <p>{{ $product->measure_cm }} cm<br>{{ $product->measure_inc }} in
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="default-sheet-box default-sheet-price">
                                            <div id="default-sheet-price" class="default-sheet-col">
                                                <p>Price</p>
                                                <div class="default-sheet-row flex-align-center">
                                                    <div class="default-sheet-row-cell">
                                                        <h4 data-price="{{ $product->price }}" data-currency="EUR">{{ $product->pretty_price }}</h4>
                                                    </div>
                                                    <div class="default-sheet-row-cell">
                                                        <select class="currency-change no-margin">
                                                            <option value="EUR" selected="selected">€</option>
                                                            <option value="USD">$</option>
                                                            <option value="GBP">£</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="default-sheet-price" class="default-sheet-col">
                                                <p>Artwork offered by</p>
                                                <div class="default-sheet-row">
                                                    <div class="default-sheet-row-cell">
                                                        <h4>
                                                            <a href="{{ route('galleries.single', [$product->gallery->slug]) }}">{{ $product->gallery->name }}</a>, {{ $product->gallery->city }}
                                                        </h4>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    @else
                        <div class="full-col-with-margin cart-item">
                            <div class="col-container">
                                <p>Your cart is empty.</p>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
        </section>

        @if($cart->items()->count())
            <section class="cart-payment">
                <div class="boxed-container">
                    <div class="col-container container-vertical-padding-bottom container-vertical-padding-top">
                        {{--Billing Address Section--}}
                        <div class="one-half-col-with-margin">
                            <!-- Cart Summary !-->
                            <div class="default-sheet-box cart-box">
                                <h4>Summary</h4>
                                <p>To obtain final shipping costs check out and complete your order</p>
                                <div class="default-sheet-row">
                                    <div class="default-sheet-row-cell">
                                        <p class="dark-text"><strong>Subtot</strong></p>
                                    </div>
                                    <div class="default-sheet-row-cell cart-subtotal">
                                        @if($promo)
                                            <p>{{ number_format($cart->total_price * (1 - ($promo->value / 100)), 2, ',', '') }} €</p>
                                        @else
                                            <p>{{ number_format($cart->total_price, 2, ',', '') }} €</p>
                                        @endif
                                    </div>
                                </div>
                                <div class="default-sheet-row">
                                    <div class="default-sheet-row-cell">
                                        <p class="dark-text"><strong>Tot</strong></p>
                                    </div>
                                    <div class="default-sheet-row-cell">
                                        <p class="dark-text cart-price cart-total">
                                            @if($promo)
                                                <strong>{{ number_format($cart->total_price * (1 - ($promo->value / 100)), 2, ',', '') }} €</strong>
                                            @else
                                                <strong>{{ number_format($cart->total_price, 2, ',', '') }} €</strong>
                                            @endif
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- Payment Method !-->
                            <a href="{{ route('orders.view.checkout') }}">
                                <button id="initiateCheckoutButton" class="black-button" type="submit">Checkout</button>
                            </a>
                        </div>
                    </div>
                </div>
            </section>
        @endif
    </section>
@endsection

resources/views/orders/frontend/thank-you-without-payment.blade.php
@extends('layouts.app')

@section('title')
    Thank you
@endsection

@section('body-class')
    thank-you
@endsection

@section('content')

    <div class="sections">
        <section id="page-header">
            <div class="container boxed-container">
                <div class="col-container-with-offset">
                    <div class="default-sheet-row">
                        <div class="default-sheet-row-cell">
                            <i class="fa fa-check main-color-txt thanks-icon"></i><h1 class="thanks-title">Thank You</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="container-vertical-padding-bottom">
            <div class="container boxed-container">
                
                <div class="default-sheet-row">
                    <p>Your request has been submitted and your shipping quote is being calculated.</p>
                </div>
                <a class="black-button" href="{{ route('home') }}">Back to home</a>
            </div>
        </section>
    </div>
@endsection