routes/web.php
    Route::get('/{section}/main/page', 'AdminController@mainPage')->name('main.page'); // controller delle intro
    Route::post('/{section}/main/page', 'AdminController@saveMainPage')->name('main.page.save'); // controller delle intro

    // Tag & Taxonomies
    Route::resource('tags', 'Tags\AdminController');
    Route::post('/ajax/tags/retrieve', 'Tags\AdminController@retrieve')->name('tags.retrieve');
    Route::post('/tags/check/if/exist', 'Tags\AdminController@checkTagIfExist')->name('tags.check.if.exist');

    // Seo Data
    Route::resource('seo-data', 'SeoData\AdminController');
    Route::post('/ajax/seo-data/retrieve', 'SeoData\AdminController@retrieve')->name('seo-data.retrieve');

    // 301 Redirects
    Route::resource('redirects', 'Redirects\AdminController');
    Route::post('/ajax/redirects/retrieve', 'Redirects\AdminController@retrieve')->name('redirects.retrieve');

    // Bulk Sections
    Route::get('bulk/upload/redirects', 'Redirects\AdminController@bulkUpload')->name('redirects.bulk.upload');
    Route::get('bulk/upload/pages', 'Bulk\AdminController@bulkUpload')->name('pages.bulk.upload');
    Route::get('bulk/download/googleshop', 'Bulk\AdminController@bulkGoogleShop')->name('googleshop.bulk.download');

    // Bulk generics XLS calls
    Route::post('bulk/upload/xls', 'Bulk\AdminController@uploadFile')->name('bulk.upload.upload.xls');
    Route::post('bulk/uploads/verify/xls/{xls_name}/type/{type}', 'Bulk\AdminController@verifyXls')->name('bulk.upload.verify.xls');
    Route::post('bulk/uploads/process/xls/{xls_name}/type/{type}', 'Bulk\AdminController@processXls')->name('bulk.upload.process.xls');
    Route::get('bulk/uploads/download/xls/{type}', 'Bulk\AdminController@downloadXls')->name('bulk.download.process.xls');
    Route::post('bulk/uploads/process/xls/{xls_name}/status', 'Bulk\AdminController@getStateProcessXls')->name('bulk.upload.process.xls.status');

    // Galleries
    Route::get('/galleries', 'Galleries\AdminController@index')->name('galleries.index');
    Route::get('/galleries/create', 'Galleries\AdminController@create')->name('galleries.create');
    Route::post('/galleries', 'Galleries\AdminController@store')->name('galleries.store');
    Route::delete('/galleries/{id}', 'Galleries\AdminController@destroy')->name('galleries.destroy');
    Route::post('/ajax/galleries/retrieve', 'Galleries\AdminController@retrieve')->name('galleries.retrieve');

    // Fairs
    Route::get('/fairs', 'Fairs\AdminController@index')->name('fairs.index');
    Route::get('/fairs/create', 'Fairs\AdminController@create')->name('fairs.create');
    Route::post('/fairs', 'Fairs\AdminController@store')->name('fairs.store');
    Route::delete('/fairs/{id}', 'Fairs\AdminController@destroy')->name('fairs.destroy');
    Route::post('/ajax/fairs/retrieve', 'Fairs\AdminController@retrieve')->name('fairs.retrieve');
    Route::any('/ajax/fairs/{id}/pdf/floorplant', 'Fairs\AdminController@floorplantManagement')->name('fairs.floorplant');

    // Categories
    Route::group(['prefix' => "categories", 'as' => 'categories.'], function () {
        Route::resource('magazine', 'Posts\CategoriesController');
        Route::post('/ajax/magazine/retrieve', 'Posts\CategoriesController@retrieve')->name('magazine.retrieve');

        Route::resource('news', 'Posts\CategoriesController');
        Route::post('/ajax/news/retrieve', 'Posts\CategoriesController@retrieve')->name('news.retrieve');

        Route::resource('galleries', 'Galleries\CategoriesController');
        Route::post('/ajax/galleries/retrieve', 'Galleries\CategoriesController@retrieve')->name('galleries.retrieve');

        Route::resource('artists', 'Artists\CategoriesController');
        Route::post('/ajax/artists/retrieve', 'Artists\CategoriesController@retrieve')->name('artists.retrieve');

        Route::resource('artworks', 'Artworks\CategoriesController');
        Route::get('artworks/create/{is_main?}', 'Artworks\CategoriesController@create')->name('artworks.create');
        Route::post('/ajax/artworks/retrieve/{is_main?}', 'Artworks\CategoriesController@retrieve')->name('artworks.retrieve');
    });

    // Medium (Category variation for Artwork)
    Route::group(['prefix' => "medium", 'as' => 'medium.'], function () {
        Route::resource('artworks', 'Artworks\MediumController');
        Route::post('/ajax/artworks/retrieve', 'Artworks\MediumController@retrieve')->name('artworks.retrieve');
    });

    // Medium / Categories relations
    Route::group(['prefix' => "artworks/medium", 'as' => 'artworks.medium.'], function () {
        Route::resource('categories', 'Artworks\CategoriesMediumController');
        Route::post('categories/ajax/retrieve', 'Artworks\CategoriesMediumController@retrieve')->name('categories.retrieve');
    });
});

// Common for Admin / Gallerist / Artist / Seo
Route::group(['middleware' => ['permission:admin-level|gallerist-level|artist-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Artworks
    Route::resource('artworks', 'Artworks\AdminController');
    Route::post('/ajax/artworks/retrieve', 'Artworks\AdminController@retrieve')->name('artworks.retrieve');

    //Artists
    Route::get('/artists/{id}/edit', 'Artists\AdminController@edit')->name('artists.edit');
    Route::patch('/artists/{id}', 'Artists\AdminController@update')->name('artists.update');

});

// Common for Admin / Gallerist / Artist / Fair / Seo
Route::group(['middleware' => ['permission:admin-level|gallerist-level|fair-level|artist-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // News
    Route::resource('news', 'Posts\AdminController');
    Route::post('/ajax/news/retrieve', 'Posts\AdminController@retrieve')->name('news.retrieve');

});

// Common for Admin / Gallerist / Seo
Route::group(['middleware' => ['permission:admin-level|gallerist-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Galleries
    Route::get('/galleries/{id}/edit', 'Galleries\AdminController@edit')->name('galleries.edit');
    Route::patch('/galleries/{id}', 'Galleries\AdminController@update')->name('galleries.update');

    // Artists
    Route::get('/artists', 'Artists\AdminController@index')->name('artists.index');
    Route::get('/artists/create', 'Artists\AdminController@create')->name('artists.create');
    Route::post('/artists', 'Artists\AdminController@store')->name('artists.store');
    Route::delete('/artists/{id}', 'Artists\AdminController@destroy')->name('artists.destroy');
    Route::post('/ajax/artists/retrieve', 'Artists\AdminController@retrieve')->name('artists.retrieve');

    // Exhibitions
    Route::resource('exhibitions', 'Exhibitions\AdminController');
    Route::post('/ajax/exhibitions/retrieve', 'Exhibitions\AdminController@retrieve')->name('exhibitions.retrieve');

});

// Common for Admin / Gallerist
Route::group(['middleware' => ['permission:admin-level|gallerist-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Notifications
    Route::get('notifications', 'Notifications\AdminController@index')->name('notifications.index');
    Route::get('notifications/mark/all/as/read', 'Notifications\AdminController@markAllAsRead')->name('notifications.mark.all.as.read');
    Route::post('/ajax/notifications/retrieve', 'Notifications\AdminController@retrieve')->name('notifications.retrieve');

    // Memberships for Gallerist
    Route::get('memberships', 'Memberships\AdminController@index')->name('memberships.index');
    Route::get('memberships/plans', 'Memberships\AdminController@plans')->name('memberships.plans');
    Route::any('memberships/billing', 'Memberships\AdminController@billing')->name('memberships.billing');
    Route::any('memberships/card', 'Memberships\AdminController@card')->name('memberships.card');
    Route::any('memberships/payment/action', 'Memberships\AdminController@paymentAction')->name('memberships.payment.action');
    Route::any('memberships/edit', 'Memberships\AdminController@edit')->name('memberships.edit');
    Route::post('memberships/deactivate', 'Memberships\AdminController@deactivate')->name('memberships.deactivate');
    Route::post('memberships/reactivate', 'Memberships\AdminController@reactivate')->name('memberships.reactivate');
    Route::post('memberships/pay/now', 'Memberships\AdminController@payNow')->name('memberships.pay.now');
    Route::any('memberships/request/change/plan', 'Memberships\AdminController@requestChangePlan')->name('memberships.request.change.plan');
    Route::post('memberships/undo/request/change/plan', 'Memberships\AdminController@undoRequestChangePlan')->name('memberships.undo.request.change.plan');
    Route::post('memberships/get/history/payment', 'Memberships\AdminController@getHistoryPayment')->name('memberships.get.history.payment');
    Route::get('memberships/view/invoice/{serial}', 'Memberships\AdminController@viewInvoice')->name('memberships.view.invoice');

    // Associate artist to itself called from gallerist
    Route::post('/ajax/associate/artist/to/me', 'Artists\AdminController@associateArtistToGallery')->name('associate.artist.to.me');

    // Download User Guide PDF
    Route::get('download/guide', 'Galleries\AdminController@downloadGuide')->name('download.guide.pdf');

});

// Common for Admin / Fairs / Seo
Route::group(['middleware' => ['permission:admin-level|fair-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Fairs
    Route::get('/fairs/{id}/edit', 'Fairs\AdminController@edit')->name('fairs.edit');
    Route::patch('/fairs/{id}', 'Fairs\AdminController@update')->name('fairs.update');

});

// Common for Admin / Editor / Seo
Route::group(['middleware' => ['permission:admin-level|editor-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Magazines
    Route::resource('magazine', 'Posts\AdminController');

app/Http/Controllers/Galleries/CategoriesController.php
<?php

namespace App\Http\Controllers\Galleries;

use App\Http\Controllers\Controller;
use App\Models\GalleriesCategory;
use App\Models\PostsCategory;
use App\Models\SiteMap;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Session;
use Validator;
use View;

class CategoriesController extends Controller
{

    private $_directory_images = 'galleries/categories';

    private $_type_url = 'GalleriesCategory';

    private $_url_prefix = '/galleries/';
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        return view('galleries.categories.index');
    }

    public function retrieve(Request $request)
    {
        $columns = array(
            0 => 'id',
            1 => 'name',
            2 => 'slug',
            3 => 'created_at',
            4 => 'options',
        );

        $totalData = PostsCategory::count();

        $totalFiltered = $totalData;

        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            $categories = GalleriesCategory::offset($start)
                ->limit($limit)
                ->orderBy($order, $dir)
                ->get();
        } else {
            $search = $request->input('search.value');

            $categories = GalleriesCategory::where('name', 'LIKE', "%{$search}%")
                ->offset($start)
                ->limit($limit)
                ->orderBy($order, $dir)
                ->get();

            $totalFiltered = GalleriesCategory::where('name', 'LIKE', "%{$search}%")
                ->count();
        }

        $data = array();
        if (!empty($categories)) {
            foreach ($categories as $category) {
                $edit = route('admin.categories.galleries.edit', $category->id);
                $delete = route('admin.categories.galleries.destroy', $category->id);

                $nestedData['id'] = $category->id;
                $nestedData['name'] = $category->name;
                $nestedData['slug'] = $category->name;
                $nestedData['created_at'] = date('j M Y h:i a', strtotime($category->created_at));
                $nestedData['options'] = (View::make('partials.datatable-options', ['edit' => $edit, 'delete' => $delete]))->render();
                $data[] = $nestedData;

            }
        }

        $json_data = array(
            "draw" => intval($request->input('draw')),
            "recordsTotal" => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data" => $data
        );

        echo json_encode($json_data);
    }

    public function create()
    {
        $category = new GalleriesCategory();
        return view('galleries.categories.create', compact('category', 'parentCategories'));
    }

    public function store(Request $request)
    {
        $response = [
            'status' => 'failed',
            'msg' => 'Ops! Something went wrong!',
        ];
        if ($request->method() == 'POST') {
            $category = GalleriesCategory::create(Input::all());
            if ($category) {
                SiteMap::create([
                    "url" => $this->_url_prefix . $category->slug,
                    "type" => $this->_type_url,
                    "referer_id" => $category->id
                ]);
                $response = [
                    'status' => 'success',
                    'directory' => $this->_directory_images,
                    'id_row' => $category->id,
                    'redirectTo' => route('admin.categories.galleries.index')
                ];
                $request->session()->flash("success", "Category with name `{$category->name}` is successful created!");
            }
        }
        return response()->json($response);
    }

    public function edit($category)
    {
        $category = GalleriesCategory::find($category);
        return view('galleries.categories.edit', compact('category', 'parentCategories'));
    }

    public function update(Request $request, $category)
    {
        $response = [
            'status' => 'failed',
            'msg' => 'Ops! Something went wrong!',
        ];
        $category = GalleriesCategory::find($category);
        if ($request->method() == 'PATCH' && $category) {
            if ($category->update(Input::all())) {

                $site_map = SiteMap::whereType($this->_type_url)->whereRefererId($category->id)->first();
                $site_map->url = $this->_url_prefix . $category->slug;
                $site_map->save();

                $response = [
                    'status' => 'success',
                    'directory' => $this->_directory_images,
                    'id_row' => $category->id,
                    'redirectTo' => route('admin.categories.galleries.index')
                ];
                $request->session()->flash("success", "Category with name `{$category->name}` is successful saved!");
            }
        }

        return response()->json($response);
    }

    public
    function destroy($category)
    {
        $category = GalleriesCategory::find($category);
        if (Storage::disk()->exists(public_path("uploads/galleries/categories/{$category->id}"))) {
            Storage::disk()->deleteDirectory(public_path("uploads/galleries/categories/{$category->id}"));
        }
        $category->delete();

        $site_map = SiteMap::whereType($this->_type_url)->whereRefererId($category->id)->first();
        $site_map->delete();

        create_redirect_301_on_delete(parse_url(route('galleries.single', [$category->slug]), PHP_URL_PATH), parse_url(route('galleries.archive.all'), PHP_URL_PATH));

        // redirect
        Session::flash('success', "Category with name `{$category->name}` is successful removed!");
        return redirect(route('admin.categories.galleries.index'));
    }

    public
    function checkTagIfExist(Request $request)
    {
        if ($request->method() == 'POST') {
            $name = strtolower($request->get('name'));
            if (Tag::whereRaw("LOWER(name) like '{$name}'")->count()) {
                return response()->json(false);
            } else {
                return response()->json(true);
            }
        }
    }
}

resources/views/galleries/admin/create.blade.php
@extends('layouts.admin')
@section('title', 'Admin | Create Gallery')
@section('page-header', 'Admin - Create Gallery')

@section('content')
    @include('galleries.admin.form', ['action' => route('admin.galleries.store'), 'method' => 'POST'])
@endsection

resources/views/galleries/admin/edit.blade.php
@extends('layouts.admin')
@section('title', "Admin | Edit Gallery `{$gallery->name}`")
@section('page-header', "Admin - Edit Gallery `{$gallery->name}`")

@section('content')
    @include('galleries.admin.form', ['action' => route('admin.galleries.update', [$gallery->id]), 'method' => 'PATCH'])
@endsection

resources/views/galleries/admin/index.blade.php
@extends('layouts.admin')
@section('title', 'Admin | Galleries')
@section('page-header', 'Galleries')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">

                @if(!roleCheck('seo'))
                    <div class="box-header">
                        <div class="pull-right">
                            <a href="{{ route('admin.galleries.create') }}">
                                <button class="btn btn-primary">Add new gallery</button>
                            </a>
                        </div>
                    </div>
                @endif
    
                <div class="box-body">
                    <table id="table-galleries" class="table table-striped dataTables" width="100%">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>Country</th>
                            <th>City</th>
                            <th>Status</th>
                            <th>Created at</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#table-galleries').DataTable({
                "scrollX": true,
                "processing": true,
                "serverSide": true,
                "stateSave": true,
                "order": [[ 7, "desc" ]],
                "ajax": {
                    "url": "{{ route('admin.galleries.retrieve') }}",
                    "dataType": "json",
                    "type": "POST",
                    "data": {_token: "{{csrf_token()}}"}
                },
                "columns": [
                    {"data": "id"},
                    {"data": "name"},
                    {"data": "email", "bSortable": false},
                    {"data": "phone"},
                    {"data": "country", "bSortable": false},
                    {"data": "city"},
                    {"data": "status"},
                    {"data": "created_at"},
                    {"data": "options", "bSortable": false}
                ],
                // aggiungo meccanismo per settare classe di ogni cella come titolo colonna
                'createdRow': function( row, data, dataIndex ) {
                    $(row).attr('id', 'row-' + dataIndex);
                },
                'columnDefs': [
                    {
                        'targets': '_all', // punto tutte le colonne
                        // 'targets': 1, // punto la seconda colonna
                        'createdCell':  function (td, cellData, rowData, row, col) {
                            var valueIndex = 0;
                            for (var k in rowData){
                                if (rowData.hasOwnProperty(k)) {
                                    console.log("Key is " + k + " index " + valueIndex);
                                    if(valueIndex == col) {
                                        $(td).attr('class', 'cell-' + k);
                                    }
                                    valueIndex++;
                                }
                            }
                        }
                        // esempio di attivazione di attributi CSS personalizzati per una singola cella 
                        // if ( cellData < 1 ) {
                        //     $(td).css('color', 'red')
                        // }
                    }
                ]

            });
        });
    </script>
@endsection