routes/web.php
Route::post('/artists/search/by', 'Artists\FrontendController@searchBy')->name('artists.search.by'); // Artworks Archive All

// Fairs
Route::get('/fairs', 'Fairs\FrontendController@intro')->name('fairs.intro'); // Fairs Intro
Route::get('/fairs/archive', 'Fairs\FrontendController@archive')->name('fairs.archive.all'); // Fairs Archive All
Route::get('/fairs/{slug_name}', 'Fairs\FrontendController@single')->name('fairs.single'); // Fairs Single

// Posts Magazine / News
Route::get('/posts/{section}', 'Posts\FrontendController@archive')->name('posts.archive.all'); // Posts Archive All
Route::get('/posts/{section}/{slug_name}', 'Posts\FrontendController@single')->name('posts.single'); // Posts Single
Route::post('/posts/{section}/load/more', 'Posts\FrontendController@loadMore')->name('posts.load.more'); // Posts Single

// Static Pages
Route::get('/pages/{slug_name}', 'Pages\FrontendController@pages')->name('pages.intro'); // Users profile

// Exhibitions
Route::get('/exhibitions', 'Exhibitions\FrontendController@archive')->name('exhibitions.archive'); // Archive
Route::get('/exhibitions/{slug_name}', 'Exhibitions\FrontendController@single')->name('exhibitions.single'); // Single
Route::post('/exhibitions/load/more', 'Exhibitions\FrontendController@loadMore')->name('exhibitions.load.more'); // Posts Single

// Tags
Route::get('/tags/{slug_name}/{type?}', 'Tags\FrontendController@single')->name('tags.single'); // Tags Single
Route::post('/tags/{section}/load/more', 'Tags\FrontendController@loadMore')->name('tags.load.more'); // Tags Single

Route::post('/search', 'FrontendController@search')->name('search'); // Posts Single
Route::get('/get/currency/{currency}', 'FrontendController@getCurrency')->name('get.currency'); // Posts Single
Route::post('/apply/promo/code', 'FrontendController@applyPromoCode')->name('apply.promo.code');
Route::post('/remove/promo/code', 'FrontendController@removePromoCode')->name('remove.promo.code');

// Access User
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login.get');
Route::post('login', 'Auth\LoginController@login')->name('login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('/activate/{token}', 'Auth\RegisterController@verifyUser')->name('verify_user');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/auth/{provider}', 'Auth\SocialController@redirectToProvider')->name('auth.social');
Route::get('/auth/{provider}/callback', 'Auth\SocialController@handleProviderCallback')->name('auth.social.callback');

// User Routes
//Route::group(['middleware' => ['permission:user-level']], function () {
//    Route::get('/user/page', 'Users\FrontendController@profile')->name('user.profile');
//    Route::post('/user/page', 'Users\FrontendController@profile')->name('user.profile');
//});

Route::post('/add/to/cart', 'Orders\FrontendController@addToCart')->name('orders.add.to.cart'); // Add to cart
Route::post('/remove/from/cart', 'Orders\FrontendController@removeFromCart')->name('orders.remove.from.cart'); // Remove from cart
Route::get('/cart', 'Orders\FrontendController@cart')->name('orders.cart'); // Add to cart
Route::get('/paypal', 'Orders\FrontendController@payPalReturn')->name('orders.paypal.callback'); // Thank you page

Route::post('/subscribe/to/newsletter', 'FrontendController@subscribeToNewsletter')->name('subscribe.to.newsletter');
Route::get('/subscription/newsletter/thank-you', 'FrontendController@subscriptionNewsletterThankYou')->name('subscription.newsletter.thank.you');

Route::post('/send/contact/message', 'FrontendController@sendContactMessage')->name('send.contact.message');
Route::get('/pay/order/{token}', 'Orders\FrontendController@payOrder')->name('orders.pay.order'); // Checkout


Route::get('/google/shopping/feed.xml', 'FrontendController@googleFeed')->name('google.feed'); // Checkout

Route::group(['middleware' => ['permission:user-level']], function () {
    //Orders
    Route::post('/get/shipping/rate', 'Orders\FrontendController@getShippingRate')->name('orders.get.shipping.rate');
    Route::get('/checkout', 'Orders\FrontendController@viewCheckout')->name('orders.view.checkout'); // Checkout
    Route::post('/checkout', 'Orders\FrontendController@checkout')->name('orders.checkout'); // Checkout
    Route::post('/checkout/pay', 'Orders\FrontendController@checkoutPay')->name('orders.checkout.pay'); // Checkout
    Route::get('/thank-you', 'Orders\FrontendController@thankYouPage')->name('orders.thank.you'); // Thank you page
    Route::get('/order/pending/thank-you', 'Orders\FrontendController@thankYouPageWithoutPayment')->name('orders.thank.you.without.payment'); // Thank you page
    Route::get('/payment/error', 'Orders\FrontendController@paymentError')->name('orders.payment.error'); // Thank you page

    Route::post('/user/ajax/save/address', 'Users\FrontendController@saveAddress')->name('users.save.address');
    Route::post('/user/ajax/save/payment', 'Users\FrontendController@savePaymentMethod')->name('users.save.payment');
    Route::post('/user/ajax/delete/address', 'Users\FrontendController@deleteAddress')->name('users.delete.address');
    Route::post('/user/ajax/delete/payment', 'Users\FrontendController@deletePaymentMethod')->name('users.delete.payment');
    Route::post('/user/ajax/promo/code', 'Users\FrontendController@applyPromoCode')->name('users.apply.promo.code');
    Route::post('/user/ajax/promo/code/remove', 'Users\FrontendController@removePromoCode')->name('users.remove.promo.code');
    Route::post('/user/ajax/add/to/collection', 'Users\FrontendController@addToCollection')->name('users.add.to.collection');
    Route::post('/user/ajax/remove/from/collection', 'Users\FrontendController@removeFromCollection')->name('users.remove.from.collection');
    Route::post('/user/ajax/create/collection', 'Users\FrontendController@createCollection')->name('users.create.collection');
    Route::post('/user/ajax/remove/collection', 'Users\FrontendController@removeCollection')->name('users.remove.collection');
    Route::post('/user/ajax/get/collection', 'Users\FrontendController@getCollection')->name('users.get.collection');
    Route::post('/user/ajax/update/collection', 'Users\FrontendController@updateCollection')->name('users.update.collection');
    Route::post('/user/ajax/update/profile', 'Users\FrontendController@updateProfile')->name('users.update.profile');
    Route::post('/user/ajax/make/offer', 'Users\FrontendController@makeAnOffer')->name('users.make.an.offer');
    Route::post('/user/ajax/info/available', 'Users\FrontendController@requestInfoOnAvailableInFair')->name('users.info.on.available');

    // Users Dashboard
    Route::get('/users/profile', 'Users\FrontendController@profile')->name('users.profile'); // Users profile
    Route::get('/users/collections', 'Users\FrontendController@collection')->name('users.collections'); // Users profile
    Route::get('/users/favourite/artworks', 'Users\FrontendController@favouriteArtworks')->name('users.favourite.artworks'); // Users profile
    Route::get('/users/favourite/artists', 'Users\FrontendController@favouriteArtists')->name('users.favourite.artists'); // Users profile
    Route::get('/users/favourite/galleries', 'Users\FrontendController@favouriteGalleries')->name('users.favourite.galleries'); // Users profile

});


/*
|--------------------------------------------------------------------------
| Backend
|--------------------------------------------------------------------------
*/

// Common for All
Route::group(['middleware' => ['permission:fair-level|gallerist-level|artist-level|editor-level|seo-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Dashboard Generics
    Route::get('/', "AdminController@index")->name('dashboard'); // dashboard iniziale
    Route::post('/users/check/email', ['laroute' => true, 'uses' => "AdminController@userCheckEmail"])->name('user.check.email'); // check email
    Route::post('/users/check/username', ['laroute' => true, 'uses' => "AdminController@userCheckUsername"])->name('user.check.username'); // check username
    Route::post('/ajax/check/slug/availability', ['laroute' => true, 'uses' => "AdminController@checkSlugAvailability"])->name('check.slug.availability'); // check slug
    Route::post('/ajax/upload/images', "AdminController@uploadImages")->name('ajax.upload.images'); // image uploader generico 

});

// Only for SuperAdmin
Route::group(['middleware' => ['permission:superadmin-level'], 'prefix' => "admin", 'as' => 'admin.'], function () {

    // Order
    Route::get('orders',  'Orders\AdminController@index')->name('orders.index');
    Route::get('orders/not/completed',  'Orders\AdminController@notCompleted')->name('orders.not.completed');
    Route::get('orders/view/{order}',  'Orders\AdminController@view')->name('orders.view');
    Route::post('orders/update/status/{order}',  'Orders\AdminController@updateOrderStatus')->name('orders.update.status');
    Route::post('/ajax/orders/retrieve/{flag}', 'Orders\AdminController@retrieve')->name('orders.retrieve');
    Route::any('orders/current/invoices/number', 'Orders\AdminController@currentInvoicesNumber')->name('orders.current.invoices.number');
    Route::get('orders/{order_id}/resend/current/mail', 'Orders\AdminController@resendMail')->name('orders.resend.current.mail');

app/Models/Artwork.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class Artwork extends Model
{
    protected $guarded = [];

    protected $appends = ['tag_ids', 'category_ids', 'fair_ids', 'gallery_name', 'artist_name', 'pretty_price'];

    protected $fillable = [
        'artist_id',
        'gallery_id',
        'created_by',
        'reference',
        'title',
        'slug',
        'from_the_series', 
        'year',
        'width',
        'height',
        'depth',
        'weight',
        'single_piece',
        'signed',
        'dated',
        'titled',
        'framed',
        'available_in_fair',
        'show_price',
        'about_the_work',
        'news',
        'status',
        'price',
        'taxable',
        'vat',
        'current_city',
        'current_zip',
        'current_country',
        'meta_title',
        'h1',
        'canonical',
        'meta_keywords',
        'meta_description',
    ];

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag', 'artworks_tags', 'artwork_id', 'tag_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Models\ArtworksCategory', 'artworks_artworks_categories', 'artwork_id', 'category_id');
    }


    public function medium()
    {
        return $this->belongsToMany('App\Models\ArtworksCategory', 'artworks_artworks_categories', 'artwork_id', 'category_id');
    }

    public function fairs()
    {
        return $this->belongsToMany('App\Models\Fair', 'artworks_fairs', 'artwork_id', 'fair_id');
    }

    public function artist()
    {
        return $this->hasOne('App\Models\Artist', 'id', 'artist_id');
    }

    public function gallery()
    {
        return $this->hasOne('App\Models\Gallery', 'id', 'gallery_id');
    }

    public function images()
    {
        return $this->hasMany('App\Models\ArtworksImage', 'artwork_id', 'id');
    }

    public function country()
    {
        return $this->hasOne('App\Models\Country', 'id', 'current_country');
    }

    public function news(){
        return $this->belongsToMany('App\Models\Post', 'posts_artworks', 'artwork_id', 'post_id');
    }

    public function getTagIdsAttribute()
    {
        return $this->tags->pluck('id')->toArray();
    }

    public function getCategoryIdsAttribute()
    {
        return $this->categories->pluck('id')->toArray();
    }

    public function getFairIdsAttribute()
    {
        return $this->fairs->pluck('id')->toArray();
    }

    public function getGalleryNameAttribute()
    {
        return $this->gallery()->first()->name;
    }

    public function getArtistNameAttribute()
    {
        $artist = $this->artist()->first();
        return $artist->last_name . " " . $artist->first_name;
    }

    public function getMediumStringAttribute()
    {
        $medium = $this->categories()->whereIsMedium(1)->pluck('name')->toArray();
        return implode(', ', $medium);
    }

    public function getMeasureCmAttribute()
    {
        return $this->width . ' x ' . $this->height . (($this->depth ? ' x ' . $this->depth : ''));
    }

    public function getMeasureIncAttribute()
    {
        return number_format(round($this->width/2.54, 2 ),2,'.',''). ' x ' . number_format(number_format(round($this->height/2.54, 2 ),2,'.','')) . (($this->depth ? ' x ' . number_format(round($this->depth/2.54, 2 ),2,'.','') : ''));
    }

    public function getNewsAttribute($value)
    {
        return $value;
    }

    public function getPrettyPriceAttribute()
    {
        $request = request();
        if(!$request->is('admin*')){
            if(Auth::user()) {
                $offer = Auth::user()->offers()->whereArtworkId($this->id)->whereStatus(2)->first();
                if($offer){
                    return number_format($offer->amount, '2', ',', '') . " €";
                }
            }
        }
        return number_format($this->price, '2', ',', '') . " €";
    }

    public function getPriceAttribute($value)
    {
        $request = request();
        if(!$request->is('admin*')){
            if(Auth::user()) {
                $offer = Auth::user()->offers()->whereArtworkId($this->id)->whereStatus(2)->first();
                if($offer){
                    return $offer->amount;
                }
            }
        }
        return $value;
    }

    public function getMainImageAttribute(){
        $image = $this->images()->orderBy('label', 'ASC')->first();
        if(!$image){
            $image = new ArtworksImage();
            $image->url = url('/images/placeholder-square-box.jpg');

            return $image;
        }
        return $image;
    }

    public function getUrlSquareBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-square-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getUrlWideBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-wide-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getUrlVerticalBoxAttribute($value)
    {
        if(!$value){
            $main = $this->getMainImageAttribute();
            if(!$main->id){
                return '/images/placeholder-vertical-box.jpg';
            }
            return $main->url;
        }
        return $value;
    }

    public function getSlugAttribute($value){
        return trim($value);
    }
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = [];

    public function items()
    {
        return $this->hasMany('App\Models\OrderItem', 'order_id', 'id');
    }

    public function user(){
        return $this->hasOne('App\Models\User','id', 'user_id');
    }

    public function promo(){
        return $this->hasOne('App\Models\PromoCode','id', 'promo_code');
    }

    public function cart(){
        return $this->hasOne('App\Services\Cart','id', 'cart_id');
    }

    public function setBillingAddress(UserAddress $userAddress){
        if($userAddress->type == 'private'){
            $this->billing_first_name = $userAddress->first_name;
            $this->billing_last_name = $userAddress->last_name;
        } else{
            $this->	billing_company_name = $userAddress->company_name;
            $this->billing_vat_number = $userAddress->vat_number;
        }
        $this->billing_fiscal_code = $userAddress->fiscal_code;
        $this->billing_email = $userAddress->email;
        $this->billing_phone = $userAddress->phone;
        $this->billing_address = $userAddress->address_1;
        $this->billing_country = $userAddress->country;
        $this->billing_country_code = $userAddress->country_code;
        $this->billing_city = $userAddress->city;
        $this->billing_state = $userAddress->state;
        $this->billing_zip = $userAddress->zip;
    }

    public function setShippingAddress(UserAddress $userAddress){
        $this->shipping_first_name = $userAddress->first_name;
        $this->shipping_last_name = $userAddress->last_name;
        $this->shipping_email = $userAddress->email;
        $this->shipping_phone = $userAddress->phone;
        $this->shipping_address = $userAddress->address_1;
        $this->shipping_country = $userAddress->country;
        $this->shipping_country_code = $userAddress->country_code;
        $this->shipping_city = $userAddress->city;
        $this->shipping_state = $userAddress->state;
        $this->shipping_zip = $userAddress->zip;
    }
}

resources/views/orders/admin/view.blade.php
@extends('layouts.admin')@section('title', 'Admin | Orders #'. $order->serial)@section('page-header', 'View Order #'. $order->serial)

@section('styles')
    <style>
        .box-header.with-border {

        }
    </style>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-info-circle"></i>
                            <h3 class="box-title">Order details</h3>
                            @if(!$order->incomplete_order)
                                <div class="pull-right">
                                    <a href="{{ route('admin.orders.resend.current.mail', [$order->id]) }}" class="btn btn-primary"><i class="fa fa-mail-reply"></i>&nbsp; Resend {{ ($order->status == 1) ? 'received' : ($order->status == 2 ? 'completed' : 'shipping') }} email</a>
                                </div>
                            @endif
                        </div>
                        <div class="box-body">
                            <div class="col-md-6">
                                Order number
                                <strong>#{{ $order->serial }}</strong> of {{ date('d/m/Y', strtotime($order->created_at)) }} carried out by {{ $order->user()->first()->last_name }} {{ $order->user()->first()->first_name }}
                                <br> Paid by {{ get_payment_method($order->payment_method) }}<br><br>
                                @if(!$order->incomplete_order)
                                    <div class="form-group">
                                        <form class="ajax-form" method="POST" action="{{ route('admin.orders.update.status', [$order->id]) }}" data-attachment="validate">
                                            @csrf
                                            <label for="status">Status </label><span class="horizontal-space-sm"></span>
                                            <select class="form-control inline order-status" name="status" {!! ($order->status == 3)? 'disabled': '' !!}>
                                                <option value="1" {!! ($order->status == 1)? 'selected="selected"': '' !!} {!! ($order->status >= 1)? 'disabled': '' !!}>Pending</option>
                                                <option value="2" {!! ($order->status == 2)? 'selected="selected"': '' !!} {!! ($order->status >= 2)? 'disabled': '' !!}>Completed</option>
                                                @if($order->status >= 2)
                                                    <option value="3" {!! ($order->status == 3)? 'selected="selected"': '' !!}>Shipped</option>
                                                @endif
                                            </select><span class="horizontal-space-sm"></span>
                                            <input class="btn btn-md btn-primary" type="submit" value="Update" disabled>
                                        </form>
                                        <br>
                                        @if($order->status == 2)
                                            <a class="btn btn-md btn-primary" href="{{ route('admin.orders.current.invoices.pdf', [$order->serial]) }}" download>Download Invoice PDF</a>
                                        @endif
                                    </div>
                                @else
                                    <div class="col-md-12 no-padding">
                                        <p><b>Status:</b> <span>{{ get_status_order($order->status)  }}</span></p>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-money"></i>
                            <h3 class="box-title">Billing Address</h3>
                        </div>
                        <div class="box-body">
                            <div class="margin">
                                @if($order->billing_first_name && $order->billing_last_name)
                                    {{ $order->billing_first_name }} {{ $order->billing_last_name }}<br>
                                @else
                                    {{ $order->billing_company_name }}<br>
                                @endif
                                @if($order->billing_fiscal_code)
                                    {{ $order->billing_fiscal_code }}<br>
                                @endif
                                @if($order->billing_vat_number)
                                    {{ $order->billing_vat_number }}<br>
                                @endif
                                {{ $order->billing_address }}<br>
                                {{ $order->billing_city }} {{ $order->billing_zip }} {{ ($order->billing_state)? ", ".$order->billing_state : '' }}
                                <br/>
                                {{ $order->billing_country }} ({{ $order->billing_country_code }})<br/>
                                {{ $order->billing_phone }}<br/> Email: <a>{{ $order->billing_email }}</a><br/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-truck"></i>
                            <h3 class="box-title">Shipping Address</h3>
                        </div>
                        <div class="box-body">
                            <div class="margin">
                                {{ $order->shipping_first_name }}  {{ $order->shipping_last_name }}<br>
                                {{ $order->shipping_address }}<br>
                                {{ $order->shipping_city }} {{ $order->shipping_zip }} {{ ($order->shipping_state)? ", ".$order->shipping_state : '' }}
                                <br/>
                                {{ $order->shipping_country }} ({{ $order->shipping_country_code }})<br/>
                                {{ $order->shipping_phone }}<br/> Email: <a>{{ $order->shipping_email }}</a><br/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-puzzle-piece"></i>
                            <h3 class="box-title">Order Items</h3>
                        </div>
                        <div class="box-body">
                            <table class="table table-bordered table-striped admin-data-table orderTable">
                                <thead>
                                <th>Image</th>
                                <th>Reference</th>
                                <th>Title</th>
                                <th>Quantity</th>
                                <th>Unit Price</th>
                                <th>Partial</th>
                                </thead>
                                <tbody>
                                @foreach($order->items()->get() as $item)
                                <tr>
                                    <td>
                                        <img src="{{$item->artwork()->first()->main_image->url }}" style="max-height: 100px" alt="">
                                    </td>
                                    <td><p>{{ $item->artwork()->first()->reference }}</p></td>
                                    <td><p>{{ $item->artwork()->first()->title }}</p></td>
                                    <td><p>{{ $item->quantity }}</p></td>
                                    <td><p>{{ $item->subtotal }} €</p></td>
                                    <td><p>{{ number_format(($item->quantity * $item->subtotal),2,'.','') }} €</p></td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-body">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <td colspan="4" width="70%"></td>
                                    <td align="right" width="20%"><strong>Subtotal</strong></td>
                                    <td width="10%" align="right"> {{ $order->subtotal }} €</td>
                                </tr>
                                @if($order->promo_code)
                                    <tr>
                                        <td colspan="4" width="70%"></td>
                                        <td align="right" width="20%"><strong>Coupon</strong></td>
                                        <td width="10%" align="right"> {{ number_format(-($order->subtotal * $order->promo()->first()->value) / 100, 2, '.', '') }} €</td>
                                    </tr>
                                @endif
                                @if(!$order->incomplete_order)
                                    <tr>
                                        <td colspan="4" width="70%"></td>
                                        <td align="right" width="20%"><strong>Shipping</strong></td>
                                        <td width="10%" align="right">{{ number_format($order->shipping,2,'.','')  }} €</td>
                                    </tr>
                                @else
                                    <tr>
                                        <td colspan="4" width="70%"></td>
                                        <td align="right" width="20%" style="vertical-align: middle"><strong>Shipping</strong></td>
                                        <td width="10%" align="right">
                                            <form id="update-shipping" class="ajax-form" method="POST" action="{{ route('admin.orders.update.shipping', [$order->id]) }}" data-attachment="validate">
                                                <input type="number" value="0.00" style="text-align: right; border: 3px solid #48b6ac" min="0" step="0.01" name="shipping" required>
                                            </form>
                                        </td>
                                    </tr>
                                @endif
                                <tr>
                                    <td colspan="4" width="70%"></td>
                                    <td align="right" width="20%"><strong>Total</strong></td>
                                    <td width="10%" align="right">{{ $order->amount }} €</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            @if($order->incomplete_order)
                <div class="row">
                    {{-- Footer & Submit --}}
                    <div class='col-md-12 col-xs-12'>
                        <div class="box box-primary box-solid">
                            <div class="box-footer">
                                <div class="pull-right ">
                                    <input class="btn btn-primary" type="submit" value="Update" form="update-shipping"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
@endsection